### ISSUE TITLE
question for unloading combine

### ISSUE THREAD

**Issue by kwguk** [Stephan-S/FS22_AutoDrive#671] opened 2022-08-30 19:48 UTC
Firstly AD is a great mod and i wouldn't play FS without it. Secondly i know nothing programming, code or mods so excuse my ignorance if this is impossible.

Is it possible to have a quick fix for two issues there is with 'unload combine' mode. 
Firstly to remove the 90% threshold which stops the tractor approaching the combine. There's many a time when my tractor is racing to unload the combine when its half way down a turn when the combine reaches 90% full and the tractor stops when if it continued it would have had ample time to offload the combine.

Secondly, there are times when the tractor wont reach the combine until it is full and stationary. Once the unloading begins the combine trys to move away but the AD tractor does not. Could this be made so the AD tractor follows the CP combine when it attempts to move off again?

many thanks

**Comment by rohne83** [comment] 2022-10-14 13:15
@Iwan1803 first part of this issue here is duplicate of #640 
Second question is about the same as in #638

Think instead of keeping all 3 issues open and losing overview, one should be enough.

**Comment by coatsy35** [comment] 2023-07-05 17:46
Just spotted this after posting my own comment about the same. Is this planned to be fixed anytime soon? Love this mod, but on big fields with combines this is really annoying when the problem kicks in. Appreciate this is all for free, but would be nice to see the outstanding issues above fixed after all this time.

**Comment by Iwan1803** [comment] 2023-07-05 22:31
Duplicate to the mentioned topic -> closed!

**Closed by Iwan1803** 2023-07-05 22:31 UTC
