### ISSUE TITLE
Cannot engage mouse to control AD console

### ISSUE THREAD

**Issue by TSO-Original** [Stephan-S/FS22_AutoDrive#553] opened 2022-05-29 14:28 UTC
Cannot engage mouse to control AD console since downloading new build.

Tried remapping, tried different maps, tested keyboard in txt editor to ensure functionality

**Comment by TSO-Original** [comment] 2022-05-29 17:41
Hold that thought, went back to previous build and still can't engage mouse. Further research is needed.

**Comment by TSO-Original** [comment] 2022-05-31 12:04
In my case, I periodically zip my save game folder and had done so recently to send to Giants for a bug report. I went back to it with the latest build of AD, and I was again able to engage mouse. After playing for awhile, I had issues with a JD Sprayer mod I had downloaded, but not with other machines.

**Comment by Iwan1803** [comment] 2022-06-01 06:16
Are you using CP? In the key binding you can find an entry for CP to release the mouse pointer which is assigned to the right mouse button. Try to delete it.

**Comment by TSO-Original** [comment] 2022-06-01 14:52
To be clear, without that JD Sprayer mod, I don't seem to have an issue with it

**Comment by TSO-Original** [comment] 2022-06-02 18:48
[Jonathan DuBois] R4045

https://www.facebook.com/groups/391651415399551/permalink/667179761180047

https://mega.nz/file/8iQWmbaD#xiC1XgyJ-xyNM2sWC13t70CuMjycjtbGlmN4aI9Y--4

**Comment by MikeSierra-AUT** [comment] 2022-06-03 15:54
I had the same problem. There is a (quite large) number of mods, which remove the middle mouse key from the keyboard/mouse/console-settings from LS22. The problem can be solved/worked around in that way, that you havew to reset the key settings of LS to default, or manually re-set the function of the middle mouse key, on every time, you install a new mod which causes this problem.
Michael.

**Comment by TSO-Original** [comment] 2022-06-03 15:59
I don't like using the middle mouse, so I add a keyboard mapping to Ctrl+Z, but when this issue occurs, that doesn't work either.

**Comment by andrewrooke** [comment] 2022-07-05 07:44
https://github.com/Stephan-S/FS22_AutoDrive/issues/583 may be a duplicate of this issue.

I can replicate this problem when I exit a vehicle when Edit mode within the AD console is open. When i re-enter a vehicle and try to engage mouse to control the AD console, I need to have AD Edit mode bound to a keyboard command to enable and disable Edit mode - which then lets me engage the mouse again.

**Comment by Iwan1803** [comment] 2023-03-12 16:42
If mods manipulate the key bindings from other mods, then contact the modders to remove this stupid function.
For leaving the vehicle while in edit mode there was a change in 2.0.0.9. So you should try the latest version.

**Closed by Iwan1803** 2023-03-12 16:42 UTC
Labels: Wait for user/feedback
