### ISSUE TITLE
Suggestion for unload combine.

### ISSUE THREAD

**Issue by jobyrns72** [Stephan-S/FS22_AutoDrive#21] opened 2021-12-19 02:53 UTC
Hello first off I want to thank y'all for the hard work bringing this to fs22 so fast! What I'm working with here is I am harvesting sugar beets and using the in game amity overloader to over load. Everything works flawlessly dumping in to trucks until it gets to its unload point and just sits there bc it doesn't get fully loaded until I hit continue. I also noticed in  fs19 and 22 that this also was the case in the load mode. I was just wondering if there was anyway to add a function like the deliver mode if the silo is empty wait and don't wait to both the combine unload and the load mode thanks a lot!!!

**Comment by Axel32019** [comment] 2021-12-22 12:57
Hello, Could you please post some screenshots of the situation where something stuck and please have the HUD visible.

**Comment by jobyrns72** [comment] 2021-12-24 04:42
![fsScreen_2021_12_23_22_25_27](https://user-images.githubusercontent.com/4283225/147316446-3009e09c-112d-448e-972f-0ea2a60c12
One update it will unload after it gets to the unload point with the update of the engine staying on. I misworded in my first post.  As you can see in my pic my overloader isnt fully empty with no trailer close.  I was just suggesting a setting that is like in the deliver mode  that if theres no trigger for like so long then continue to the next point. It would be useful in high yielding crops or when loading lime or fertilizer from a trailer in the load mode. This is pretty realistic in real life too. So pretty much a timer setting for unload point in unload combine mode and timer setting for load point in load mode. I hope this makes more sense. Thanks love the mod by the way!

**Comment by Stephan-S** [comment] 2021-12-28 15:51
Basically now a duplicate of #10 now. Closed

**Closed by Stephan-S** 2021-12-28 15:51 UTC
Labels: question
